import sqlmodel

"""adding community keys

Revision ID: 05d84f746fc7
Revises: 
Create Date: 2025-02-18 18:37:32.975434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "05d84f746fc7"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "group", sa.Column("community_keys", sa.ARRAY(sa.String()), nullable=True)
    )
    op.create_index(
        "idx_group_community_keys",
        "group",
        ["community_keys"],
        unique=False,
        postgresql_using="gin",
    )
    op.alter_column(
        "kbtopic",
        "start_time",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "kbtopic",
        "start_time",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
    )
    op.drop_index(
        "idx_group_community_keys", table_name="group", postgresql_using="gin"
    )
    op.drop_column("group", "community_keys")
    # ### end Alembic commands ###
